const fortuneQuotesquotes = [
  "Qualunque cosa tu possa fare o sognare di poter fare, incominciala. (Johann Wolfgang von Goethe)",
  "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni. (Eleanor Roosevelt)",
  "Fra vent’anni non sarete delusi dalle cose che avrete fatto, ma da quelle che non avrete fatto. (Mark Twain)",
  "Non è perché le cose sono difficili che non osiamo, è perché non osiamo che sono difficili. (Seneca)",
  "Fai della tua vita un sogno, e di un sogno, una realtà. (Antoine de Saint-Exupéry)",
  "Tutti i nostri sogni possono diventare realtà se abbiamo il coraggio di perseguirli. (Walt Disney)",
  "Il passo più difficile è sempre il primo. (Proverbio popolare)",
  "Non aspettare. Il tempo non sarà mai 'giusto'. (Napoleon Hill)",
  "L'inizio è la parte più importante del lavoro. (Platone)",
  "Osare è perdere l'equilibrio per un attimo. Non osare è perdere sé stessi. (Søren Kierkegaard)",
  "Cadi sette volte, rialzati otto. (Proverbio Giapponese)",
  "Non arrenderti mai, perché quando pensi che sia finita, è proprio allora che tutto ha inizio. (Jim Morrison)",
  "La gloria più grande non consiste nel non cadere mai, ma nel rialzarsi ogni volta che cadiamo. (Confucio)",
  "Se puoi sognarlo, puoi farlo. (Walt Disney)",
  "Il successo è l'abilità di passare da un fallimento all'altro senza perdere l'entusiasmo. (Winston Churchill)",
  "I sogni non svaniscono, finché le persone non li abbandonano. (Richard Nixon)",
  "Il mondo è nelle mani di coloro che hanno il coraggio di sognare e di correre il rischio di vivere i propri sogni. (Paulo Coelho)",
  "Non farti spingere dai tuoi problemi. Fatti guidare dai tuoi sogni. (Ralph Waldo Emerson)",
  "La perseveranza è il duro lavoro che fai dopo che ti sei stancato del duro lavoro che hai fatto. (Newt Gingrich)",
  "Solo chi sogna può volare. (James Matthew Barrie)",
  "Diventa ciò che sei. (Friedrich Nietzsche)",
  "Dove c’è una grande volontà, non possono esserci grandi difficoltà. (Niccolò Machiavelli)",
  "La felicità non è qualcosa di già pronto. Viene dalle tue azioni. (Dalai Lama)",
  "L’unico modo per fare un ottimo lavoro è amare quello che fate. (Steve Jobs)",
  "Conosci te stesso. (Socrate)",
  "La vita è un’avventura audace o non è nulla. (Helen Keller)",
  "Pensa, credi, sogna e osa. (Walt Disney)",
  "Non guardare l'orologio; fa' ciò che fa lui. Continua ad andare avanti. (Sam Levenson)",
  "La speranza è il sogno di chi è sveglio. (Aristotele)",
  "Agisci come se quel che fai facesse la differenza. La fa. (William James)",
  "I sogni sono le illustrazioni dal libro che la tua anima sta scrivendo su di te. (Marsha Norman)",
  "Nulla accade a meno che prima non sia un sogno. (Carl Sandburg)",
  "Segui il tuo destino, stringi i tuoi sogni e non mollare mai. (Anonimo)",
  "Siamo fatti della stessa materia di cui sono fatti i sogni. (William Shakespeare)",
  "Un vincitore è un sognatore che non si è mai arreso. (Nelson Mandela)",
  "Vola solo chi osa farlo. (Luis Sepúlveda)",
  "La realtà è sbagliata, i sogni sono reali. (Tupac Shakur)",
  "Tenetevi stretti ai sogni, perché se i sogni muoiono, la vita è un uccello con le ali spezzate che non può volare. (Langston Hughes)",
  "C'è un solo modo per dimenticare il tempo: impiegarlo. (Charles Baudelaire)",
  "Vai con fiducia nella direzione dei tuoi sogni. Vivi la vita che hai immaginato. (Henry David Thoreau)",
  "Sii il cambiamento che vuoi vedere nel mondo. (Mahatma Gandhi)",
  "L'uomo è ciò che crede. (Anton Čechov)",
  "La tua visione diventerà chiara solo quando guarderai nel tuo cuore. (Carl Jung)",
  "I limiti esistono solo nell'anima di chi è a corto di sogni. (Anonimo)",
  "Punta alla luna. Anche se sbagli, atterrerai tra le stelle. (Les Brown)",
  "Il segreto per andare avanti è iniziare. (Mark Twain)",
  "Non lasciare che il rumore delle opinioni altrui offuschi la tua voce interiore. (Steve Jobs)",
  "Tutto ciò che hai sempre desiderato è dall'altra parte della paura. (George Addair)",
  "Le persone che sono abbastanza folli da pensare di poter cambiare il mondo, sono coloro che lo fanno davvero. (Rob Siltanen)",
  "Non è mai troppo tardi per essere ciò che avresti potuto essere. (George Eliot)",
  "Chi sogna di giorno conosce molte cose che sfuggono a chi sogna solo di notte. (Edgar Allan Poe)",
  "La vita è troppo breve per essere piccoli. (Benjamin Disraeli)",
  "L'entusiasmo è la base di ogni progresso. (Henry Ford)",
  "Nulla è davvero difficile se lo si divide in piccoli pezzi. (Henry Ford)",
  "Se non costruisci il tuo sogno, qualcuno ti assumerà per costruire il suo. (Dhirubhai Ambani)",
  "Non smettere mai di sognare, solo chi sogna può volare. (Peter Pan)",
  "Mira in alto, perché le stelle sono nascoste nella tua anima. (Pamela Vaull Starr)",
  "Il miglior modo per predire il futuro è crearlo. (Peter Drucker)",
  "Fai quello che puoi, con quello che hai, dove sei. (Theodore Roosevelt)",
  "I sogni sono le risposte di oggi alle domande di domani. (Edgar Cayce)",
  "La logica vi porterà da A a B. L'immaginazione vi porterà dappertutto. (Albert Einstein)",
  "Sii te stesso; tutti gli altri sono già stati presi. (Oscar Wilde)",
  "Ciò che la mente può concepire e credere, può realizzare. (Napoleon Hill)",
  "L'unico limite alla nostra realizzazione di domani saranno i nostri dubbi di oggi. (Franklin D. Roosevelt)",
  "Niente è impossibile, la parola stessa dice 'Io sono possibile'. (Audrey Hepburn)",
  "Preferisco morire di passione che di noia. (Vincent van Gogh)",
  "Ogni grande sogno inizia con un sognatore. (Harriet Tubman)",
  "Il successo non è la chiave della felicità. La felicità è la chiave del successo. (Albert Schweitzer)",
  "Vivi come se dovessi morire domani. Impara come se dovessi vivere per sempre. (Mahatma Gandhi)",
  "Non contare i giorni, fa' che i giorni contino. (Muhammad Ali)",
  "Un viaggio di mille miglia inizia con un solo passo. (Lao Tzu)",
  "L'immaginazione è più importante della conoscenza. (Albert Einstein)",
  "L'uomo che sposta le montagne inizia portando via i sassi più piccoli. (Confucio)",
  "Dobbiamo accettare la delusione finita, ma non dobbiamo mai perdere la speranza infinita. (Martin Luther King Jr.)",
  "La libertà è la possibilità di dubitare, di cercare, di dire di no a qualsiasi autorità. (Ignazio Silone)",
  "Non guardare indietro. Non è lì che stai andando. (Anonimo)",
  "L'ottimista vede opportunità in ogni pericolo. (Winston Churchill)",
  "Sogna come se dovessi vivere per sempre. Vivi come se dovessi morire oggi. (James Dean)",
  "L’ostacolo è il percorso. (Proverbio Zen)",
  "C’è una forza motrice più forte di vapore ed elettricità: la volontà. (Albert Einstein)",
  "Un uomo non è vecchio finché i rimpianti non prendono il posto dei sogni. (John Barrymore)",
  "I sogni sono necessari per vivere. (Anaïs Nin)",
  "La felicità è reale solo quando è condivisa. (Christopher McCandless)",
  "Il rischio più grande è non correre nessun rischio. (Mark Zuckerberg)",
  "Non dire mai che i sogni sono inutili, inutile è la vita di chi non sa sognare. (Jim Morrison)",
  "I sogni diventano realtà se li desideri abbastanza. (James Matthew Barrie)",
  "Il coraggio è il giudizio che qualcos'altro è più importante della paura. (Ambrose Redmoon)",
  "Sogna in grande e osa fallire. (Norman Vaughan)",
  "L'azione è la chiave fondamentale di ogni successo. (Pablo Picasso)",
  "Non fermarti quando sei stanco, fermati quando hai finito. (Marilyn Monroe)",
  "Credi in te stesso e in tutto ciò che sei. (Christian D. Larson)",
  "Sii fedele a ciò che esiste dentro di te. (André Gide)",
  "Il desiderio è il punto di partenza di ogni conquista. (Napoleon Hill)",
  "Ogni artista è stato prima un dilettante. (Ralph Waldo Emerson)",
  "Il fallimento è solo l'opportunità di ricominciare in modo più intelligente. (Henry Ford)",
  "La vita è per il 10% cosa ti accade e per il 90% come reagisci. (Charles R. Swindoll)",
  "Non lasciare che ciò che non puoi fare interferisca con ciò che puoi fare. (John Wooden)",
  "Quello che facciamo oggi è ciò che conta di più. (Buddha)",
  "Mantenere i propri sogni vivi è il compito più difficile. (Anonimo)",
  "Chi non può sentire la musica ritiene pazzi quelli che danzano. (Friedrich Nietzsche)"
]
function manu(){
   let frase = Math.floor(Math.random() * fortuneQuotes.length)
   document.getElementById('giorgia').innerText = fortuneQuotes[frase]
}
manu()